tasks:
  - name: ts-graph
    init: |
      cd ts-graph |
      yarn install
    command: yarn run dev

  - name: docker-compose
    init: docker-compose pull
    command: docker-compose up
ports:
  - port: 7474
    onOpen: open-browser
  - port: 7687
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
