version: "3.9"

services:
  neo4j:
    image: "neo4j:4.4.8"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/pass
    restart: always